# -*- coding: utf-8 -*-
"""Iris Flower Classification(Task-1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDMoU5yXDagDGf5pQOSSqofkVM1YmLPJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv("/content/Iris.csv")
df.drop(columns="Id", inplace=True)
df.head()

sns.pairplot(df, hue="Species")
plt.show()

sns.heatmap(df.drop("Species", axis=1).corr(), annot=True, cmap="coolwarm")
plt.show()

X = df.drop("Species", axis=1)
y = df["Species"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

lr = LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)

svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

models = {
    "Logistic Regression": lr,
    "SVM": svm,
    "Decision Tree": dt,
    "KNN": knn
}

for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))

param_grid = {
    'n_neighbors': [3,5,7,9],
    'weights': ['uniform', 'distance']
}

grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)

cv_scores = cross_val_score(svm, X_scaled, y, cv=10)
print("Cross Validation Accuracy:", cv_scores.mean())

y_pred = svm.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, cmap="Blues",
            xticklabels=df['Species'].unique(),
            yticklabels=df['Species'].unique())
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Take user input
sepal_length = float(input("Enter Sepal Length (cm): "))
sepal_width  = float(input("Enter Sepal Width (cm): "))
petal_length = float(input("Enter Petal Length (cm): "))
petal_width  = float(input("Enter Petal Width (cm): "))

# Create DataFrame with feature names
user_input_df = pd.DataFrame(
    [[sepal_length, sepal_width, petal_length, petal_width]],
    columns=X.columns
)

# Scale input
user_input_scaled = scaler.transform(user_input_df)

# Predict
prediction = svm.predict(user_input_scaled)
print("\n🌸 Predicted Iris Species:", prediction[0])