# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python(Task-2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eJHcfzFifscE7gO8-p9XIAN_yWWUYmI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")

# Load dataset
df = pd.read_csv("/content/Unemployment in India.csv")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Remove extra spaces from Date values
df['Date'] = df['Date'].str.strip()

# Convert Date column (DD-MM-YYYY)
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Rename columns for clean usage
df.rename(columns={
    'Estimated Unemployment Rate (%)': 'Unemployment_Rate',
    'Estimated Employed': 'Employed',
    'Estimated Labour Participation Rate (%)': 'Labour_Participation_Rate'
}, inplace=True)

# -------------------- BASIC CHECKS --------------------
print(df.head())
print(df.info())
print(df.isnull().sum())

plt.figure(figsize=(10,5))
sns.lineplot(data=df, x='Date', y='Unemployment_Rate')
plt.title("Unemployment Rate Trend in India")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.show()

covid_data = df[df['Date'].dt.year == 2020]

plt.figure(figsize=(10,5))
sns.lineplot(data=covid_data, x='Date', y='Unemployment_Rate', hue='Area')
plt.title("Unemployment Rate During COVID-19 (2020)")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.show()

region_avg = (
    df.groupby("Region")["Unemployment_Rate"]
    .mean()
    .sort_values(ascending=False)
)

plt.figure(figsize=(12,6))
region_avg.plot(kind='bar')
plt.title("Average Unemployment Rate by Region")
plt.ylabel("Unemployment Rate (%)")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='Area', y='Unemployment_Rate')
plt.title("Urban vs Rural Unemployment Rate")
plt.xlabel("Area")
plt.ylabel("Unemployment Rate (%)")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df,
    x='Labour_Participation_Rate',
    y='Unemployment_Rate',
    hue='Area'
)
plt.title("Labour Participation vs Unemployment")
plt.xlabel("Labour Participation Rate (%)")
plt.ylabel("Unemployment Rate (%)")
plt.show()